name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release -o <C:/Users/isms/Desktop/myapp/index.html>

      - name: Deploy to IIS
        run: |
          # PowerShell script to deploy the application to IIS
          # Adjust the parameters as per your requirements

          # Import IIS module
          Import-Module WebAdministration

          # Define variables
          $siteName = "<http://localhost/mywebserver/>"
          $appPoolName = "<DefaultAppPool>"
          $physicalPath = "<C:\Users\isms\Desktop\myapp>"

          # Check if site already exists
          $existingSite = Get-WebSite -Name $siteName -ErrorAction SilentlyContinue

          # Create new application pool
          $newAppPool = New-WebAppPool -Name $appPoolName

          # Create new site if not exists
          if (!$existingSite) {
            New-WebSite -Name $siteName -PhysicalPath $physicalPath -ApplicationPool $newAppPool
          } else {
            Set-WebConfiguration -Filter '/system.applicationHost/sites/site[@name='$siteName']/application' -Value @{path='/';physicalPath=$physicalPath}
          }

          # Start site
          Start-WebSite -Name $siteName

          # Restart app pool
          Restart-WebAppPool -Name $appPoolName
